services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - sureid_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017/?authSource=admin"
    networks:
      - sureid_network
    volumes:
      - ./backend:/app  # Mount local backend directory into container's /app directory
      - /app/__pycache__  # Optional: prevent overriding __pycache__


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"  # Map container's port 3000 to host's port 3000
    depends_on:
      - backend
    networks:
      - sureid_network
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules

volumes:
  mongo_data:

networks:
  sureid_network:
    name: sureid_network
    driver: bridge
